project:
  title: "Sprague Recipe Collection"
  type: website
  output-dir: docs
  
  # GitHub Pages configuration
  render:
    - "index.md"
    - "export/*.md"
    - "!export/CLAUDE.md"
    - "!export/claude.md"
  
  resources:
    - "export/assets/"
    - ".nojekyll"

website:
  title: "Sprague Recipe Collection"
  description: "Our family's tested recipe collection"
  site-url: "https://richardsprague.github.io/Food"
  repo-url: https://github.com/richardsprague/Food
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.md
        text: Home
      - text: "Sous Vide"
        href: "export/Summary- Sous Vide.md"
      - text: "Instant Pot"  
        href: "export/Instant Pot Bone Broth.md"
      - text: "Breads"
        href: "export/Sourdough Bread.md"
    right:
      - icon: github
        href: https://github.com/richardsprague
        aria-label: GitHub
  sidebar:
    style: docked
    background: light
    contents:
      - section: "Featured Recipes"
        contents:
          - "export/Pressure Cooker Pork Belly (Kakuni).md"
          - "export/Sourdough Bread.md"
          - "export/Sous Vide Chicken.md"
          - "export/Minestrone (Instant Pot).md"
      - section: "Proteins"
        contents:
          - text: "Chicken Recipes"
            contents:
              - "export/Baked Sambal-Spiced Marinated Chicken Thighs.md"
              - "export/Blue Apron- Yuzu and Honey-Glazed Chicken Thighs.md"
              - "export/Chicken Thighs Morocco and Barley.md"
              - "export/Instant Pot Chicken Marsala.md"
              - "export/Moroccan style Chicken.md"
              - "export/Ricotta Chicken.md"
              - "export/Sous Vide Chicken.md"
          - text: "Seafood"
            contents:
              - "export/Anchovy Salad.md"
              - "export/Baked Shrimp.md"
              - "export/Blue Apron- Sheet Pan Spicy Maple-Mustard Salmon.md"
              - "export/Honey-garlic shrimp.md"
              - "export/Miso-Ginger Marinade for Salmon.md"
              - "export/Sous Vide- Salmon.md"
              - "export/Tilapia with Miso and Scallions.md"
          - text: "Pork & Beef"
            contents:
              - "export/Filipino Pork Afritada.md"
              - "export/Middle Eastern Beef Meatballs.md"
              - "export/Pressure Cooker Pork Belly (Kakuni).md"
              - "export/Sous Vide- Beef.md"
              - "export/Sous Vide- Pork.md"
      - section: "Vegetarian"
        contents:
          - "export/Black Bean Tofu.md"
          - "export/Cream Pesto Lentils.md"
          - "export/Daal- Lentils and Spinach.md"
          - "export/French Lentils stuffed Poblano.md"
          - "export/Hummus.md"
          - "export/Mexican Black Bean Chorizo.md"
      - section: "Breads & Baking"
        contents:
          - "export/Almond Flour Bread.md"
          - "export/Corn Tortillas.md"
          - "export/Hamburger buns in 40 minutes.md"
          - "export/Low Sugar Pumpkin Bread.md"
          - "export/Naan.md"
          - "export/Sourdough Bread.md"
          - "export/Sourdough Focaccia.md"

format:
  html:
    theme: minty
    css: css/normalize.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: true
    # GitHub Pages specific settings
    page-layout: article
    title-block-banner: false
  
execute:
  freeze: auto
  
# Additional GitHub Pages settings can be added here
