project:
  title: "Sprague Recipe Collection"
  type: website
  output-dir: docs
  
  # GitHub Pages configuration
  render:
    - "*.md"
    - "content/*.md"
    - "!CLAUDE.md"
    - "!content/claude.md"
  
  resources:
    - "assets/"
    - ".nojekyll"

website:
  title: "Sprague Recipe Collection"
  description: "Our family's tested recipe collection"
  site-url: "https://richardsprague.github.io/Food"
  repo-url: https://github.com/richardsprague/Food
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.md
        text: Home
      - text: "Sous Vide"
        href: "content/Summary- Sous Vide.md"
      - text: "Instant Pot"  
        href: "content/Instant Pot Bone Broth.md"
      - text: "Breads"
        href: "content/Sourdough Bread.md"
    right:
      - icon: github
        href: https://github.com/richardsprague
        aria-label: GitHub
  sidebar:
    style: docked
    background: light
    contents:
      - section: "Featured Recipes"
        contents:
          - "content/Pressure Cooker Pork Belly (Kakuni).md"
          - "content/Sourdough Bread.md"
          - "content/Sous Vide Chicken.md"
          - "content/Minestrone (Instant Pot).md"
      - section: "Proteins"
        contents:
          - text: "Chicken Recipes"
            contents:
              - "content/Baked Sambal-Spiced Marinated Chicken Thighs.md"
              - "content/Blue Apron- Yuzu and Honey-Glazed Chicken Thighs.md"
              - "content/Chicken Thighs Morocco and Barley.md"
              - "content/Instant Pot Chicken Marsala.md"
              - "content/Moroccan style Chicken.md"
              - "content/Ricotta Chicken.md"
              - "content/Sous Vide Chicken.md"
          - text: "Seafood"
            contents:
              - "content/Anchovy Salad.md"
              - "content/Baked Shrimp.md"
              - "content/Blue Apron- Sheet Pan Spicy Maple-Mustard Salmon.md"
              - "content/Honey-garlic shrimp.md"
              - "content/Miso-Ginger Marinade for Salmon.md"
              - "content/Sous Vide- Salmon.md"
              - "content/Tilapia with Miso and Scallions.md"
          - text: "Pork & Beef"
            contents:
              - "content/Filipino Pork Afritada.md"
              - "content/Middle Eastern Beef Meatballs.md"
              - "content/Pressure Cooker Pork Belly (Kakuni).md"
              - "content/Sous Vide- Beef.md"
              - "content/Sous Vide- Pork.md"
      - section: "Vegetarian"
        contents:
          - "content/Black Bean Tofu.md"
          - "content/Cream Pesto Lentils.md"
          - "content/Daal- Lentils and Spinach.md"
          - "content/French Lentils stuffed Poblano.md"
          - "content/Hummus.md"
          - "content/Mexican Black Bean Chorizo.md"
      - section: "Breads & Baking"
        contents:
          - "content/Almond Flour Bread.md"
          - "content/Corn Tortillas.md"
          - "content/Hamburger buns in 40 minutes.md"
          - "content/Low Sugar Pumpkin Bread.md"
          - "content/Naan.md"
          - "content/Sourdough Bread.md"
          - "content/Sourdough Focaccia.md"

format:
  html:
    theme: minty
    css: css/normalize.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: true
    # GitHub Pages specific settings
    page-layout: article
    title-block-banner: false
  
execute:
  freeze: auto
  
# Additional GitHub Pages settings can be added here
